version: '2'
services:
  django-dev-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:8000
    volumes:
      - ./app:/app
    command: python3 manage.py runserver 0.0.0.0:8000
    links: 
      - redis
  django-celery-worker:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    command: celery -A main_app worker -l info --concurrency=1
    links: 
      - redis
  redis:
    image: redis:latest

